//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.13 at 02:56:27 PM EDT 
//


package com.systemsinmotion.petfinder.entities;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.systemsinmotion.petfinder.entities package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.systemsinmotion.petfinder.entities
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link PetfinderPetRecord }
     * 
     */
    public PetfinderPetRecord createPetfinderPetRecord() {
        return new PetfinderPetRecord();
    }

    /**
     * Create an instance of {@link PetfinderPetRecord.Media }
     * 
     */
    public PetfinderPetRecord.Media createPetfinderPetRecordMedia() {
        return new PetfinderPetRecord.Media();
    }

    /**
     * Create an instance of {@link PetfinderHeaderType }
     * 
     */
    public PetfinderHeaderType createPetfinderHeaderType() {
        return new PetfinderHeaderType();
    }

    /**
     * Create an instance of {@link Petfinder }
     * 
     */
    public Petfinder createPetfinder() {
        return new Petfinder();
    }

    /**
     * Create an instance of {@link PetfinderAuthData }
     * 
     */
    public PetfinderAuthData createPetfinderAuthData() {
        return new PetfinderAuthData();
    }

    /**
     * Create an instance of {@link PetfinderPetIdList }
     * 
     */
    public PetfinderPetIdList createPetfinderPetIdList() {
        return new PetfinderPetIdList();
    }

    /**
     * Create an instance of {@link PetfinderPetRecordList }
     * 
     */
    public PetfinderPetRecordList createPetfinderPetRecordList() {
        return new PetfinderPetRecordList();
    }

    /**
     * Create an instance of {@link PetfinderBreedList }
     * 
     */
    public PetfinderBreedList createPetfinderBreedList() {
        return new PetfinderBreedList();
    }

    /**
     * Create an instance of {@link PetfinderShelterRecord }
     * 
     */
    public PetfinderShelterRecord createPetfinderShelterRecord() {
        return new PetfinderShelterRecord();
    }

    /**
     * Create an instance of {@link PetfinderShelterRecordList }
     * 
     */
    public PetfinderShelterRecordList createPetfinderShelterRecordList() {
        return new PetfinderShelterRecordList();
    }

    /**
     * Create an instance of {@link PetContactType }
     * 
     */
    public PetContactType createPetContactType() {
        return new PetContactType();
    }

    /**
     * Create an instance of {@link PetPhotoType }
     * 
     */
    public PetPhotoType createPetPhotoType() {
        return new PetPhotoType();
    }

    /**
     * Create an instance of {@link PetfinderPetRecord.Options }
     * 
     */
    public PetfinderPetRecord.Options createPetfinderPetRecordOptions() {
        return new PetfinderPetRecord.Options();
    }

    /**
     * Create an instance of {@link PetfinderPetRecord.Media.Photos }
     * 
     */
    public PetfinderPetRecord.Media.Photos createPetfinderPetRecordMediaPhotos() {
        return new PetfinderPetRecord.Media.Photos();
    }

    /**
     * Create an instance of {@link PetfinderHeaderType.Status }
     * 
     */
    public PetfinderHeaderType.Status createPetfinderHeaderTypeStatus() {
        return new PetfinderHeaderType.Status();
    }

}
